spring:
  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres
    username: postgres.aseqwraeapulbkkutpfs
    password: Administrador*2025
  jpa:
    hibernate:
      ddl-auto: validate    